# Generated by Django 6.0.7 on 2026-07-28 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nama sumber')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='kode')),
                ('description', models.TextField(blank=True, verbose_name='keterangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sumber data',
                'verbose_name_plural': 'sumber data',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExternalApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nama aplikasi')),
                ('prefix', models.CharField(editable=False, max_length=12, unique=True)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token API eksternal',
                'verbose_name_plural': 'token API eksternal',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=150, verbose_name='referensi')),
                ('status', models.CharField(choices=[('processing', 'Diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='processing', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='verification.datasource')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StagedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=190, verbose_name='kunci data SIMRS')),
                ('record_type', models.CharField(db_index=True, max_length=80, verbose_name='jenis data')),
                ('raw_data', models.JSONField(verbose_name='data asli')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('in_review', 'Sedang diperiksa'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak')], db_index=True, default='pending', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='verification.importbatch')),
            ],
            options={
                'ordering': ('-imported_at',),
            },
        ),
        migrations.CreateModel(
            name='VerifiedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified_data', models.JSONField(verbose_name='data hasil verifikasi')),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('approved', 'Disetujui'), ('published', 'Dipublikasikan'), ('rejected', 'Ditolak')], db_index=True, default='draft', max_length=20)),
                ('verification_notes', models.TextField(blank=True, verbose_name='catatan verifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('staged_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verified_record', to='verification.stagedrecord')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VerificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='verification.verifiedrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='stagedrecord',
            index=models.Index(fields=['record_type', 'status'], name='verificatio_record__a0fe28_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagedrecord',
            constraint=models.UniqueConstraint(fields=('batch', 'source_key'), name='unique_source_key_per_batch'),
        ),
    ]
