# Generated by Django 6.0.7 on 2026-07-29 00:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientIndicatorSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='Tanggal pertama bulan laporan', unique=True, verbose_name='periode')),
                ('period_start', models.DateField(verbose_name='tanggal awal')),
                ('period_end', models.DateField(verbose_name='tanggal akhir')),
                ('days_in_period', models.PositiveSmallIntegerField(verbose_name='jumlah hari')),
                ('beds', models.PositiveIntegerField(verbose_name='tempat tidur')),
                ('care_days', models.PositiveIntegerField(verbose_name='hari perawatan')),
                ('discharged_patients', models.PositiveIntegerField(verbose_name='pasien keluar')),
                ('deaths', models.PositiveIntegerField(verbose_name='pasien meninggal')),
                ('deaths_over_48h', models.PositiveIntegerField(verbose_name='meninggal > 48 jam')),
                ('alos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gdr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ndr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_response', models.JSONField(verbose_name='respons asli API')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('fetched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data asli indikator rawat inap',
                'ordering': ('-period',),
            },
        ),
        migrations.CreateModel(
            name='VerifiedInpatientIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='periode')),
                ('alos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ALOS (hari)')),
                ('bor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='BOR (%)')),
                ('bto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='BTO (kali)')),
                ('toi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TOI (hari)')),
                ('gdr', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GDR (per 1.000)')),
                ('ndr', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='NDR (per 1.000)')),
                ('notes', models.TextField(blank=True, verbose_name='catatan')),
                ('status', models.CharField(choices=[('draft', 'Sedang diperiksa'), ('approved', 'Terverifikasi')], default='draft', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='verification.inpatientindicatorsource')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hasil verifikasi indikator rawat inap',
                'ordering': ('-period',),
            },
        ),
        migrations.CreateModel(
            name='InpatientIndicatorAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('before_data', models.JSONField(null=True)),
                ('after_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='verification.verifiedinpatientindicator')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
