# Generated by Django 6.0.7 on 2026-07-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_inpatientindicatorsource_verifiedinpatientindicator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatientindicatorsource',
            name='raw_response',
            field=models.JSONField(verbose_name='hasil asli query'),
        ),
    ]
