# Generated by Django 6.0.7 on 2026-07-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_alter_inpatientindicatorsource_raw_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatientindicatorsource',
            name='calculated_alos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ALOS hitung Django'),
        ),
        migrations.AddField(
            model_name='inpatientindicatorsource',
            name='calculated_bor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BOR hitung Django'),
        ),
        migrations.AddField(
            model_name='inpatientindicatorsource',
            name='calculated_bto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BTO hitung Django'),
        ),
        migrations.AddField(
            model_name='inpatientindicatorsource',
            name='calculated_gdr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='GDR hitung Django'),
        ),
        migrations.AddField(
            model_name='inpatientindicatorsource',
            name='calculated_ndr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='NDR hitung Django'),
        ),
        migrations.AddField(
            model_name='inpatientindicatorsource',
            name='calculated_toi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TOI hitung Django'),
        ),
        migrations.AlterField(
            model_name='inpatientindicatorsource',
            name='raw_response',
            field=models.JSONField(verbose_name='respons asli PHP'),
        ),
    ]
