# Generated by Django 6.0.7 on 2026-08-05 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_inpatientindicatorsource_calculated_alos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyHealthIndicatorSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(unique=True, verbose_name='periode')),
                ('hospital_code', models.CharField(max_length=40, verbose_name='kode rumah sakit')),
                ('hospital_name', models.CharField(max_length=180, verbose_name='nama rumah sakit')),
                ('source_data', models.JSONField(verbose_name='data sumber ternormalisasi')),
                ('raw_response', models.JSONField(verbose_name='respons asli API')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('fetched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data sumber indikator kesehatan bulanan',
                'verbose_name_plural': 'data sumber indikator kesehatan bulanan',
                'ordering': ('-period',),
            },
        ),
        migrations.CreateModel(
            name='VerifiedMonthlyHealthIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='periode')),
                ('verified_data', models.JSONField(verbose_name='data hasil verifikasi')),
                ('status', models.CharField(choices=[('draft', 'Sedang diperiksa'), ('approved', 'Terverifikasi')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='catatan')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='verification.monthlyhealthindicatorsource')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hasil verifikasi indikator kesehatan bulanan',
                'verbose_name_plural': 'hasil verifikasi indikator kesehatan bulanan',
                'ordering': ('-period',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyHealthIndicatorAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('before_data', models.JSONField(null=True)),
                ('after_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='verification.verifiedmonthlyhealthindicator')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
