# Generated by Django 6.0.7 on 2026-08-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_monthlyhealthindicatorsource_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifiedinpatientindicator',
            options={'ordering': ('-period',), 'permissions': (('approve_verifiedinpatientindicator', 'Can approve verified inpatient indicator'),), 'verbose_name': 'hasil verifikasi indikator rawat inap'},
        ),
        migrations.AlterModelOptions(
            name='verifiedmonthlyhealthindicator',
            options={'ordering': ('-period',), 'permissions': (('approve_verifiedmonthlyhealthindicator', 'Can approve verified monthly health indicator'),), 'verbose_name': 'hasil verifikasi indikator kesehatan bulanan', 'verbose_name_plural': 'hasil verifikasi indikator kesehatan bulanan'},
        ),
        migrations.AlterModelOptions(
            name='verifiedrecord',
            options={'ordering': ('-updated_at',), 'permissions': (('approve_verifiedrecord', 'Can approve verified record'),)},
        ),
    ]
