# Generated by Django 6.0.7 on 2026-08-06 00:41

from django.conf import settings
from django.db import migrations, models


def fill_existing_health_periods(apps, schema_editor):
    from calendar import monthrange
    Source = apps.get_model("verification", "MonthlyHealthIndicatorSource")
    for source in Source.objects.filter(period_start__isnull=True):
        source.period_start = source.period
        source.period_end = source.period.replace(day=monthrange(source.period.year, source.period.month)[1])
        source.save(update_fields=("period_start", "period_end"))


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0008_remove_patient_satisfaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatientindicatorsource',
            name='period_type',
            field=models.CharField(default='month', max_length=12, verbose_name='jenis periode'),
        ),
        migrations.AddField(
            model_name='monthlyhealthindicatorsource',
            name='period_end',
            field=models.DateField(null=True, verbose_name='tanggal akhir'),
        ),
        migrations.AddField(
            model_name='monthlyhealthindicatorsource',
            name='period_start',
            field=models.DateField(null=True, verbose_name='tanggal awal'),
        ),
        migrations.AddField(
            model_name='monthlyhealthindicatorsource',
            name='period_type',
            field=models.CharField(default='month', max_length=12, verbose_name='jenis periode'),
        ),
        migrations.AlterField(
            model_name='inpatientindicatorsource',
            name='period',
            field=models.DateField(help_text='Tanggal awal laporan', verbose_name='periode'),
        ),
        migrations.AlterField(
            model_name='monthlyhealthindicatorsource',
            name='period',
            field=models.DateField(verbose_name='periode'),
        ),
        migrations.RunPython(fill_existing_health_periods, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inpatientindicatorsource',
            constraint=models.UniqueConstraint(fields=('period_type', 'period_start', 'period_end'), name='unique_inpatient_reporting_period'),
        ),
        migrations.AddConstraint(
            model_name='monthlyhealthindicatorsource',
            constraint=models.UniqueConstraint(fields=('period_type', 'period_start', 'period_end'), name='unique_health_reporting_period'),
        ),
    ]
