# Generated by Django 6.0.7 on 2026-08-06 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0009_flexible_reporting_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedDiseaseGroupRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('icd10_range', models.CharField(max_length=80)),
                ('patient_count', models.PositiveIntegerField(default=0)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_group_rows', to='verification.verifiedmonthlyhealthindicator')),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(fields=('verification', 'code'), name='unique_verified_disease_group_row')],
            },
        ),
        migrations.CreateModel(
            name='VerifiedHealthVisitRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=30)),
                ('count', models.PositiveIntegerField(default=0)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_rows', to='verification.verifiedmonthlyhealthindicator')),
            ],
            options={
                'ordering': ('installation', 'payment_status'),
                'constraints': [models.UniqueConstraint(fields=('verification', 'installation', 'payment_status'), name='unique_verified_health_visit_row')],
            },
        ),
        migrations.CreateModel(
            name='VerifiedTopDiseaseRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation', models.CharField(max_length=20)),
                ('rank', models.PositiveSmallIntegerField()),
                ('icd10_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('patient_count', models.PositiveIntegerField(default=0)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_disease_rows', to='verification.verifiedmonthlyhealthindicator')),
            ],
            options={
                'ordering': ('installation', 'rank'),
                'constraints': [models.UniqueConstraint(fields=('verification', 'installation', 'rank'), name='unique_verified_top_disease_rank')],
            },
        ),
        migrations.CreateModel(
            name='VerifiedTouristVisitRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=160)),
                ('count', models.PositiveIntegerField(default=0)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_visit_rows', to='verification.verifiedmonthlyhealthindicator')),
            ],
            options={
                'ordering': ('category', 'origin'),
                'constraints': [models.UniqueConstraint(fields=('verification', 'category', 'origin'), name='unique_verified_tourist_visit_row')],
            },
        ),
    ]
