# Generated by Django 6.0.7 on 2026-08-06 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0011_backfill_normalized_health_rows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimrsApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('inpatient-indicators', 'Indikator Rawat Inap'), ('health-aggregate', 'Indikator Kesehatan (Agregat)'), ('visits', 'Kunjungan Pasien'), ('top-diseases', '10 Penyakit Terbanyak'), ('tourist-visits', 'Kunjungan Wisatawan'), ('disease-groups', 'Kelompok Penyakit')], max_length=40, unique=True, verbose_name='kode endpoint')),
                ('name', models.CharField(max_length=160, verbose_name='nama endpoint')),
                ('url', models.URLField(max_length=500, verbose_name='URL API')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30, verbose_name='timeout (detik)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_simrs_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'endpoint API SIMRS',
                'verbose_name_plural': 'endpoint API SIMRS',
                'ordering': ('code',),
            },
        ),
    ]
