# Generated by Django 6.0.7 on 2026-08-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0014_endpoint_admin_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importbatch',
            name='source',
        ),
        migrations.RemoveField(
            model_name='importbatch',
            name='imported_by',
        ),
        migrations.RemoveIndex(
            model_name='stagedrecord',
            name='verificatio_record__a0fe28_idx',
        ),
        migrations.RemoveConstraint(
            model_name='stagedrecord',
            name='unique_source_key_per_batch',
        ),
        migrations.RemoveField(
            model_name='verifiedrecord',
            name='staged_record',
        ),
        migrations.RemoveField(
            model_name='verificationaudit',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='verificationaudit',
            name='record',
        ),
        migrations.RemoveField(
            model_name='verifiedrecord',
            name='verified_by',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.RemoveField(
            model_name='stagedrecord',
            name='batch',
        ),
        migrations.DeleteModel(
            name='VerificationAudit',
        ),
        migrations.DeleteModel(
            name='VerifiedRecord',
        ),
        migrations.DeleteModel(
            name='ImportBatch',
        ),
        migrations.DeleteModel(
            name='StagedRecord',
        ),
    ]
