# Generated by Django 6.0.7 on 2026-08-07 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


INDICATOR_CODES = (
    'outpatient-visits', 'inpatient-visits', 'emergency-visits',
    'top-diseases', 'tourist-visits', 'cancer-patients',
    'heart-patients', 'stroke-patients', 'uronephrology-patients',
)


def create_indicator_verifications(apps, schema_editor):
    Verified = apps.get_model('verification', 'VerifiedMonthlyHealthIndicator')
    Indicator = apps.get_model('verification', 'HealthIndicatorVerification')
    rows = []
    for record in Verified.objects.all().iterator():
        for code in INDICATOR_CODES:
            rows.append(Indicator(
                record_id=record.pk,
                indicator_code=code,
                status=record.status,
                notes=record.notes,
                verified_by_id=record.verified_by_id,
                verified_at=record.verified_at,
            ))
    Indicator.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0020_add_village_region_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthIndicatorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(max_length=40, verbose_name='indikator')),
                ('status', models.CharField(choices=[('draft', 'Sedang diperiksa'), ('approved', 'Terverifikasi'), ('rejected', 'Ditolak')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='catatan')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_verifications', to='verification.verifiedmonthlyhealthindicator')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-record__period', 'indicator_code'),
                'constraints': [models.UniqueConstraint(fields=('record', 'indicator_code'), name='unique_health_indicator_verification')],
            },
        ),
        migrations.RunPython(create_indicator_verifications, migrations.RunPython.noop),
    ]
