# Generated by Django 6.0.7 on 2026-08-07 23:59

from django.db import migrations


KJSU_CODES = (
    'cancer-patients', 'heart-patients', 'stroke-patients',
    'uronephrology-patients',
)


def merge_kjsu(apps, schema_editor):
    Indicator = apps.get_model('verification', 'HealthIndicatorVerification')
    record_ids = Indicator.objects.filter(
        indicator_code__in=KJSU_CODES
    ).values_list('record_id', flat=True).distinct()
    for record_id in record_ids.iterator():
        rows = list(Indicator.objects.filter(
            record_id=record_id, indicator_code__in=KJSU_CODES
        ).order_by('-verified_at', '-updated_at'))
        if not rows:
            continue
        statuses = {row.status for row in rows}
        status = 'approved' if statuses == {'approved'} else (
            'rejected' if 'rejected' in statuses else 'draft'
        )
        latest = rows[0]
        notes = '\n'.join(dict.fromkeys(row.notes for row in rows if row.notes))
        Indicator.objects.update_or_create(
            record_id=record_id,
            indicator_code='kjsu-evaluation',
            defaults={
                'status': status,
                'notes': notes,
                'verified_by_id': latest.verified_by_id,
                'verified_at': latest.verified_at if status == 'approved' else None,
            },
        )
        Indicator.objects.filter(
            record_id=record_id, indicator_code__in=KJSU_CODES
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0021_healthindicatorverification'),
    ]

    operations = [
        migrations.RunPython(merge_kjsu, migrations.RunPython.noop),
    ]
