# Generated by Django 6.0.7 on 2026-08-08 03:30

from django.db import migrations, models


def copy_source_to_working_data(apps, schema_editor):
    Verified = apps.get_model('verification', 'VerifiedInpatientIndicator')
    for record in Verified.objects.select_related('source').iterator():
        source = record.source
        record.working_beds = source.beds
        record.working_care_days = source.care_days
        record.working_discharged_patients = source.discharged_patients
        record.working_deaths = source.deaths
        record.working_deaths_over_48h = source.deaths_over_48h
        record.working_days_in_period = source.days_in_period
        record.save(update_fields=(
            'working_beds', 'working_care_days', 'working_discharged_patients',
            'working_deaths', 'working_deaths_over_48h', 'working_days_in_period',
        ))


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0022_merge_kjsu_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedinpatientindicator',
            name='working_beds',
            field=models.PositiveIntegerField(default=0, verbose_name='tempat tidur data kerja'),
        ),
        migrations.AddField(
            model_name='verifiedinpatientindicator',
            name='working_care_days',
            field=models.PositiveIntegerField(default=0, verbose_name='hari perawatan data kerja'),
        ),
        migrations.AddField(
            model_name='verifiedinpatientindicator',
            name='working_days_in_period',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='jumlah hari data kerja'),
        ),
        migrations.AddField(
            model_name='verifiedinpatientindicator',
            name='working_deaths',
            field=models.PositiveIntegerField(default=0, verbose_name='kematian data kerja'),
        ),
        migrations.AddField(
            model_name='verifiedinpatientindicator',
            name='working_deaths_over_48h',
            field=models.PositiveIntegerField(default=0, verbose_name='kematian >48 jam data kerja'),
        ),
        migrations.AddField(
            model_name='verifiedinpatientindicator',
            name='working_discharged_patients',
            field=models.PositiveIntegerField(default=0, verbose_name='pasien keluar data kerja'),
        ),
        migrations.RunPython(copy_source_to_working_data, migrations.RunPython.noop),
    ]
