# Generated by Django 6.0.7 on 2026-08-08 03:56

from django.db import migrations


def normalize_code(value):
    code = str(value or '').strip()
    lengths = {2: (2,), 4: (2, 2), 6: (2, 2, 2), 10: (2, 2, 2, 4)}.get(len(code))
    if not code.isdigit() or not lengths:
        return code
    parts, offset = [], 0
    for length in lengths:
        parts.append(code[offset:offset + length])
        offset += length
    return '.'.join(parts)


def remap_integer_codes(apps, schema_editor):
    Region = apps.get_model('verification', 'AdministrativeRegion')
    TouristRow = apps.get_model('verification', 'VerifiedTouristVisitRow')
    region_ids = dict(Region.objects.filter(is_active=True).values_list('official_code', 'id'))
    for row in TouristRow.objects.exclude(origin_code='').iterator():
        normalized = normalize_code(row.origin_code)
        region_id = region_ids.get(normalized)
        update_fields = []
        if normalized != row.origin_code:
            row.origin_code = normalized
            update_fields.append('origin_code')
        if region_id and row.region_id != region_id:
            row.region_id = region_id
            row.cleaning_method = 'official_code'
            update_fields.extend(('region', 'cleaning_method'))
        if update_fields:
            row.save(update_fields=tuple(dict.fromkeys(update_fields)))


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0023_verifiedinpatientindicator_working_beds_and_more'),
    ]

    operations = [
        migrations.RunPython(remap_integer_codes, migrations.RunPython.noop),
    ]
