# Generated by Django 6.0.7 on 2026-08-08 04:19

import django.db.models.deletion
from django.db import migrations, models


def seed_inpatient_rooms_endpoint(apps, schema_editor):
    Endpoint = apps.get_model('verification', 'SimrsApiEndpoint')
    total = Endpoint.objects.filter(code='inpatient-indicators').first()
    if not total:
        return
    url = total.url
    replacements = (
        ('get_rawat_api.php', 'get_rawat_per_ruang_api.php'),
        ('data_indikator_ranap.php', 'data_indikator_per_bangsal.php'),
    )
    for old, new in replacements:
        if old in url:
            url = url.replace(old, new)
            break
    Endpoint.objects.get_or_create(
        code='inpatient-rooms',
        defaults={
            'name': 'Indikator Rawat Inap per Ruang',
            'url': url,
            'is_active': True,
            'timeout_seconds': total.timeout_seconds,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0024_remap_integer_region_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simrsapiendpoint',
            name='code',
            field=models.CharField(choices=[('inpatient-indicators', 'Indikator Rawat Inap'), ('inpatient-rooms', 'Indikator Rawat Inap per Ruang'), ('visits', 'Kunjungan Pasien'), ('top-diseases', '10 Penyakit Terbanyak'), ('tourist-visits', 'Kunjungan Wisatawan'), ('disease-groups', 'Kelompok Penyakit')], max_length=40, unique=True, verbose_name='kode endpoint'),
        ),
        migrations.CreateModel(
            name='InpatientRoomIndicatorSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=40, verbose_name='kode ruang')),
                ('room_name', models.CharField(max_length=180, verbose_name='nama ruang')),
                ('is_special', models.BooleanField(default=False, verbose_name='ruang khusus')),
                ('beds', models.PositiveIntegerField(verbose_name='tempat tidur')),
                ('care_days', models.PositiveIntegerField(verbose_name='hari perawatan')),
                ('discharged_patients', models.PositiveIntegerField(verbose_name='pasien keluar')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='pasien meninggal')),
                ('deaths_over_48h', models.PositiveIntegerField(default=0, verbose_name='meninggal >48 jam')),
                ('alos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gdr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ndr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_sources', to='verification.inpatientindicatorsource')),
            ],
            options={
                'ordering': ('room_name',),
            },
        ),
        migrations.CreateModel(
            name='VerifiedInpatientRoomIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gdr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ndr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_room', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='verification.inpatientroomindicatorsource')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_indicators', to='verification.verifiedinpatientindicator')),
            ],
            options={
                'ordering': ('source_room__room_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='inpatientroomindicatorsource',
            constraint=models.UniqueConstraint(fields=('source', 'room_code'), name='unique_inpatient_room_source'),
        ),
        migrations.RunPython(seed_inpatient_rooms_endpoint, migrations.RunPython.noop),
    ]
