# Generated by Django 6.0.7 on 2026-08-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0025_alter_simrsapiendpoint_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatientindicatorsource',
            name='calculated_alos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ALOS hitung DataHub'),
        ),
        migrations.AlterField(
            model_name='inpatientindicatorsource',
            name='calculated_bor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BOR hitung DataHub'),
        ),
        migrations.AlterField(
            model_name='inpatientindicatorsource',
            name='calculated_bto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BTO hitung DataHub'),
        ),
        migrations.AlterField(
            model_name='inpatientindicatorsource',
            name='calculated_gdr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='GDR hitung DataHub'),
        ),
        migrations.AlterField(
            model_name='inpatientindicatorsource',
            name='calculated_ndr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='NDR hitung DataHub'),
        ),
        migrations.AlterField(
            model_name='inpatientindicatorsource',
            name='calculated_toi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TOI hitung DataHub'),
        ),
        migrations.AlterField(
            model_name='inpatientindicatorsource',
            name='raw_response',
            field=models.JSONField(verbose_name='respons asli SIMRS'),
        ),
    ]
