# Generated by Django 5.2.7 on 2026-08-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=190)),
                ('product_code', models.CharField(db_index=True, max_length=120)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('remote_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'audit akses API',
                'verbose_name_plural': 'audit akses API',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApiProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True, verbose_name='kode produk')),
                ('name', models.CharField(max_length=160, verbose_name='nama')),
                ('description', models.TextField(blank=True, verbose_name='keterangan')),
                ('required_scope', models.CharField(max_length=160, verbose_name='scope wajib')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'produk API eksternal',
                'verbose_name_plural': 'produk API eksternal',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ExternalApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=190, unique=True, verbose_name='OAuth client ID')),
                ('name', models.CharField(max_length=160, verbose_name='nama aplikasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('requests_per_minute', models.PositiveIntegerField(default=60, verbose_name='request per menit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'client API eksternal',
                'verbose_name_plural': 'client API eksternal',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExternalApiGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='berakhir pada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='api_access.externalapiclient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='api_access.apiproduct')),
            ],
            options={
                'verbose_name': 'izin client eksternal',
                'verbose_name_plural': 'izin client eksternal',
                'constraints': [models.UniqueConstraint(fields=('client', 'product'), name='unique_external_client_product')],
            },
        ),
    ]
