# Generated by Django 6.0.7 on 2026-08-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='is_simadu_official',
            field=models.BooleanField(default=False, help_text='Status terakhir dari field pejabat pada endpoint api/me SIMADU.', verbose_name='pejabat SIMADU'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='official_status_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='status pejabat diperiksa pada'),
        ),
    ]
