"""
Django settings for dash project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-development-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'verification',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dash.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Makassar'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'verification:dashboard'
LOGOUT_REDIRECT_URL = 'login'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# PHP merupakan satu-satunya jembatan ke SIMRS; Django tidak membuka koneksi DB SIMRS.
SIMRS_INDICATOR_API_URL = os.environ.get("SIMRS_INDICATOR_API_URL", "")

# OAuth opaque SIMADU: DataHub sebagai client saat membaca API PHP/SIMRS.
SIMADU_TOKEN_URL = os.environ.get("SIMADU_TOKEN_URL", "")
SIMADU_CLIENT_ID = os.environ.get("SIMADU_CLIENT_ID", "")
SIMADU_CLIENT_SECRET = os.environ.get("SIMADU_CLIENT_SECRET", "")
SIMADU_SIMRS_SCOPE = os.environ.get(
    "SIMADU_SIMRS_SCOPE", "simrs.indicators.read"
)

# OAuth opaque SIMADU: DataHub sebagai resource server untuk API pihak ketiga.
SIMADU_INTROSPECTION_URL = os.environ.get("SIMADU_INTROSPECTION_URL", "")
SIMADU_INTROSPECTION_CLIENT_ID = os.environ.get(
    "SIMADU_INTROSPECTION_CLIENT_ID", ""
)
SIMADU_INTROSPECTION_CLIENT_SECRET = os.environ.get(
    "SIMADU_INTROSPECTION_CLIENT_SECRET", ""
)
DATAHUB_API_REQUIRED_SCOPE = os.environ.get(
    "DATAHUB_API_REQUIRED_SCOPE", "datahub.indicators.read"
)
SIMADU_ALLOWED_API_CLIENTS = {
    value.strip()
    for value in os.environ.get("SIMADU_ALLOWED_API_CLIENTS", "").split(",")
    if value.strip()
}
SIMADU_OAUTH_TIMEOUT = int(os.environ.get("SIMADU_OAUTH_TIMEOUT", "10"))
SIMADU_INTROSPECTION_CACHE_SECONDS = min(
    int(os.environ.get("SIMADU_INTROSPECTION_CACHE_SECONDS", "30")), 60
)

# Cookie/HTTPS hardening otomatis aktif ketika mode production digunakan.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
